apiVersion: v1
kind: ServiceAccount
metadata:
  name: pvtracker-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvtracker-role
rules:
- apiGroups: ["cndev.nl"]
  resources: ["volumetrackers", "volumetrackers/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pvtracker-binding
subjects:
- kind: ServiceAccount
  name: pvtracker-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: pvtracker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvtracker
  namespace: default
  labels:
    app: pvtracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pvtracker
  template:
    metadata:
      labels:
        app: pvtracker
    spec:
      serviceAccountName: pvtracker-sa
      containers:
      - name: pvtracker
        image: ghcr.io/bartvanbenthem/pvtracker:v0.6.1
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: nfs-volume
            mountPath: /pvtrackerlog
      volumes:
        - name: nfs-volume
          nfs:
            server: 10.205.159.135
            path: /shares/fsc-pvtracker-log