apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pvtracker-role
rules:
  - apiGroups: ["cndev.nl"]
    resources: ["volumetrackers", "volumetrackers/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims", "persistentvolumes", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
