apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: volumetrackers.cndev.nl
spec:
  group: cndev.nl
  names:
    kind: VolumeTracker
    plural: volumetrackers
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          properties:
            metadata:
              type: object
            spec:
              type: object
              properties:
                clusterNameKey:
                  type: string
                mountPath:
                  type: string
                retention:
                  type: integer
              required:
                - clusterNameKey
            status:
              type: object
              properties:
                succeeded:
                  type: boolean
          required:
            - spec
      served: true
      storage: true
      subresources:
        # status enables the status subresource.
        status: {}