namespace: dr-operator

serviceAccount:
  name: pvtracker-sa

image:
  repository: ghcr.io/bartvanbenthem/pvtracker
  tag: v0.6.1
  pullPolicy: IfNotPresent

nfs:
  server: 10.205.159.135
  path: /shares/fsc-pvtracker-log
  mountPath: /pvtrackerlog # needs to corresponed with the mountPath given in the volumeTracker spec
