use garde::Validate;
use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Struct corresponding to the Specification (`spec`) part of the `CDBootstrap` resource, directly
/// reflects context of the `cdbootstraps.example.com.yaml` file to be found in this repository.
/// The `CDBootstrap` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, Validate, Clone, Default, JsonSchema)]
#[kube(
    group = "cndev.nl",
    version = "v1beta1",
    kind = "VolumeTracker",
    plural = "volumetrackers",
    namespaced
)]
#[kube(status = "VolumeTrackerStatus")]
pub struct TrackerSpec {
    #[garde(skip)]
    #[serde(rename = "clusterNameKey")]
    pub cluster_name_key: String,
    #[garde(skip)]
    #[serde(rename = "mountPath")]
    pub mount_path: String,
    #[garde(skip)]
    #[serde(rename = "retention")]
    pub retention: u16,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default, JsonSchema)]
pub struct Annotation {
    pub key: String,
    pub value: String,
}

#[derive(Deserialize, Serialize, Clone, Debug, Default, JsonSchema)]
pub struct VolumeTrackerStatus {
    pub succeeded: bool,
}
